site_name: DEMONs Musical Stairs Documentation
site_description: Documentation geared towards understanding the majority of the files, and how to use them.
theme: 'material'
pages:
- ['index.md', 'Index']
